### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Markw27348** [XYZ3211/ManeuverNodeController#1]
Does not open menu when hitting Alt + N. Spacewarp v0.1.0.

**Comment by kbmulligan** [comment]
Same for me.

**Comment by XYZ3211** [comment]
I just tested with Space Warp v0.1.0 and it is working on my install. Could you enter the Space Warp mod menu (ALT + M) and verify that you see "maneuver_node_controller" listed?

**Comment by kbmulligan** [comment]
I didn't change anything, but yes it works for me now.
