### ISSUE TITLE
[FEATURE REQUEST] Add Maneuver Node

### ISSUE THREAD

**Issue by schlosrat** [XYZ3211/ManeuverNodeController#6]
As this mod currently works it requires a maneuver node to already exist for one to be edited/updated, however, it can and will allow the player to modify an existing null node (one that has been created without any Dv defined yet).

It would be nice to be able to add a node if there isn't already one defined. Instead of merely displaying "The active vessel has no maneuver nodes." add a button to create a node. Once created, the mod should then switch to its normal mode enabling the player to edit the node.

**Comment by XYZ3211** [comment]
Thanks for contributing this feature!
